[workspace]
authors = ["JarningGau <jarninggau@gmail.com>"]
channels = ["https://mirrors2.westlake.edu.cn/ANACONDA/cloud/conda-forge", "https://mirrors2.westlake.edu.cn/ANACONDA/cloud/bioconda"]
name = "methscan"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
methscan = ">=1.1.0, <2"

[pypi-options]
index-url = "https://mirrors2.westlake.edu.cn/pypi/simple"