[workspace]
authors = ["JarningGau <jarninggau@gmail.com>"]
channels = ["https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge", "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda"]
name = "methscan"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
methscan = ">=1.1.0, <2"
